### PR TITLE
Feature/Custom Stages

### PR DESCRIPTION
**Pull request by akshithg**

### CODE REVIEW

**Comment by dazzaji** [comment]
Just checking - is the deleted "flexible-forms"branch dev work somewhere else now?

**Comment by akshithg** [comment]
I’ve merged it with the master.
Its more of a `custom stage name` branch. More to be added for it to be truly flexible form.

Akshith G

**Comment by dazzaji** [comment]
Ok, now I get it!  Thanks.

---

   |   Daniel "Dazza" Greenwood http://dazzagreenwood.com/
   |   CIVICS.com http://civics.com/ & Law.MIT.edu http://law.mit.edu/
   |   dazza@CIVICS.com & 617.500.3644
   |   1 Broadway, 14th Floor, Cambridge, MA 02142

**Comment by akshithg** [comment]
Hey Dazza,

Should we get on a call now so that I can take you through the deployment   process?
I have also documented it on the README. Almost the same like the old deployment except for one step.

Akshith G

**Pull request merged**
